// src/components/molecules/list/CategoryListItem.svelte
<script lang="ts">
	import GreyBackgroundButton from "../../atoms/buttons/GreyBackgroundButton.svelte";
	import Image from "../../atoms/images/Image.svelte";
	import BorderedInput from "../../atoms/inputs/BorderedInput.svelte";
	import Text from "../../atoms/texts/Text.svelte";
	import ListItemLayout from "../../layouts/ListItemLayout.svelte";
	import type { CategoryItem, SelectType } from "../../utils/Types";
	import Select from "../search/Select.svelte";
	import APIs from "../../utils/APIs";

	export let item: CategoryItem = {
		id: -1,
		name: "제목",
		productCount: "상품수",
		useYn: true,
		recommendNum: "순위",
		thumbnailImageUrl: "src\\assets\\svelte.svg",
	};
	const isActive: SelectType[] = [
		{ id: 1, name: "Y", value: true },
		{ id: 2, name: "N", value: false },
	];
	let selectedIsActive: SelectType = item.useYn ? isActive[0] : isActive[1];
	let file: Blob;
	let inputElement;

	const modifyImg = () => {
		inputElement.click();
	};
	const fileHandler = (e) => {
		file = e.target.files[0];
		item.thumbnailImageUrl = URL.createObjectURL(file);
	};

	const modify: () => void = () => {
		let option = {
			id: item.id,
			name: item.name,
			recommendNum: item.recommendNum,
			useYn: selectedIsActive.value,
		};
		APIs.editCategory(option).then((res) => {
			if (res.status === 200) {
				if (file) {
					let frm = new FormData();
					frm.append("files", file, `${item.id}_${file.name}`);
					APIs.editCategoryImg(frm, item.id).then((res) => {
						if (res.status === 200) alert("수정 완료");
					});
				} else {
					alert("수정 완료");
				}
			}
		});
	};
</script>

<ListItemLayout gap="2%">
	<Text width="10%">{item.id}</Text>
	<BorderedInput bind:value={item.name} width="30%" fontSize="16px" />
	<Text width="10%">{item.productCount}</Text>
	<Select
		lists={isActive}
		bind:selected={selectedIsActive}
		width="10%"
		height="30px"
		fontSize="16px"
	/>
	<BorderedInput fontSize="16px" bind:value={item.recommendNum} width="10%" />
	<button on:click={modifyImg}>
		<Image src={item.thumbnailImageUrl} />
		<input
			accept="image/*"
			bind:this={inputElement}
			type="file"
			bind:value={file}
			on:change={fileHandler}
		/>
	</button>
	<GreyBackgroundButton height="30px" fontSize="16px" onClick={modify}
		>수정</GreyBackgroundButton
	>
</ListItemLayout>

<style>
	button {
		width: 12%;
		text-align: center;
	}
	input {
		display: none;
	}
</style>

// src/components/molecules/listitem/CategoryListItem.tsx
import React, { useEffect, useRef, useState } from "react";
import Flex from "../../atoms/Layouts/Flex";
import Text from "../../atoms/Text/Text";
import Input from "../../atoms/Input/Input";
import Button from "../../atoms/Button/Button";
import Radio from "../../atoms/Radio/Radio";
import styled from "styled-components";

type Props = {
  category: any;
  edit: any;
  editIcon: any;
};

const CategoryListItem = ({ category, edit, editIcon }: Props) => {
  const inpRef = useRef<HTMLInputElement>(null);
  const [item, setItem] = useState<any>(category);
  const [icon, setIcon] = useState<Blob>();
  const fetchIcon = async () => {
    setIcon(await fetch(category.thumbnailImageUrl).then((r) => r.blob()));
  };
  useEffect(() => {
    if (category.thumbnailImageUrl !== null) {
      fetchIcon();
    }
  }, []);

  return (
    <Flex height="50px">
      <Text width="15%">{category.id}</Text>
      <Input
        align="center"
        width="25%"
        value={item.name}
        onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
          setItem({ ...item, name: e.target.value });
        }}
      />
      <Text width="15%">{category.productCount}</Text>
      <Radio
        name={category.name}
        align="center"
        width="15%"
        list={["Y", "N"]}
        value={item.useYn ? "Y" : "N"}
        onChange={(val: string) => {
          if (val === "Y") setItem({ ...item, useYn: true });
          else setItem({ ...item, useYn: false });
        }}
      />
      <Input
        align="center"
        width="15%"
        value={item.recommendNum}
        onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
          let x = parseInt(e.target.value);
          setItem({ ...item, recommendNum: isNaN(x) ? 0 : x });
        }}
      />
      <Flex width="15%" align="center">
        <Button
          width="15%"
          onClick={() => {
            inpRef.current?.click();
          }}>
          {icon && (
            <img
              width={30}
              height={30}
              src={URL.createObjectURL(icon)}
              alt="icon"
            />
          )}
          <Inp
            ref={inpRef}
            type="file"
            name="icons"
            onChange={(e) => {
              setIcon(e.target.files![0]);
              editIcon(e.target.files![0], item);
            }}
          />
        </Button>
      </Flex>
      <Flex width="15%" align="center">
        <Button
          color="green"
          onClick={() => {
            edit(item);
          }}>
          수정
        </Button>
      </Flex>
    </Flex>
  );
};

const Inp = styled.input`
  display: none;
`;

export default CategoryListItem;
