// src/components/molecules/list/PartnerListItem.svelte
<script lang="ts">
	import LinkedTwoValueText from "../../atoms/links/LinkedTwoValueText.svelte";
	import Text from "../../atoms/texts/Text.svelte";
	import ListItemLayout from "../../layouts/ListItemLayout.svelte";

	interface Partner {
		id: string;
		userId: string;
		nickName: string;
		grade: number;
		ceoName: string;
		phoneNumber: string;
		reviewCnt: number;
		saleCnt: number;
		productCnt: number;
		state: boolean;
	}

	export let item: Partner = {
		id: "코드",
		userId: "이메일",
		nickName: "닉네임",
		grade: -1,
		ceoName: "대표자",
		phoneNumber: "연락처",
		reviewCnt: 0,
		saleCnt: 0,
		productCnt: 0,
		state: true,
	};

	let grade = ["우수", "보통", "관리 요망"];
</script>

<ListItemLayout>
	<Text width="10%">{item.id}</Text>
	<LinkedTwoValueText
		to="/partner/{item.id}"
		width="20%"
		val1={item.userId}
		val2={item.nickName}
	/>
	<Text width="10%">{grade[item.grade]}</Text>
	<Text width="10%">{item.ceoName}</Text>
	<Text width="10%">{item.phoneNumber}</Text>
	<Text width="10%">{item.reviewCnt.toLocaleString()}</Text>
	<Text width="10%">{item.saleCnt.toLocaleString()}</Text>
	<Text width="10%">{item.productCnt.toLocaleString()}</Text>
	<Text width="10%">{item.state ? "정상" : "오류"}</Text>
</ListItemLayout>

// src/components/molecules/listitem/PartnerListItem.tsx
import React from "react";
import Flex from "../../atoms/Layouts/Flex";
import Text from "../../atoms/Text/Text";
import { Link } from "react-router-dom";
import { PartnerGrade } from "../../../libs/Constants";

type Props = {
  partner: any;
};

const PartnerListItem = ({ partner }: Props) => {
  return (
    <Flex height="50px">
      <Text width="10%">
        <Link to={`/adm/partner/${partner.id}`}>{partner.id}</Link>
      </Text>
      <Flex width="20%" direction="column" gap="0px">
        <Link to={`/adm/partner/${partner.id}`}>
          <Text>{partner.nickName}</Text>
          <Text color="grey">({partner.userId})</Text>
        </Link>
      </Flex>
      <Text width="10%">{PartnerGrade[partner.grade]}</Text>
      <Text width="10%">{partner.ceoName}</Text>
      <Text width="10%">{partner.phoneNumber}</Text>
      <Text width="10%">
        {typeof partner.reviewCnt === "number"
          ? partner.reviewCnt.toLocaleString()
          : partner.reviewCnt}
      </Text>
      <Text width="10%">
        {typeof partner.saleCnt === "number"
          ? partner.saleCnt.toLocaleString()
          : partner.saleCnt}
      </Text>
      <Text width="10%">
        {typeof partner.productCnt === "number"
          ? partner.productCnt.toLocaleString()
          : partner.productCnt}
      </Text>
      <Text width="10%">{partner.state ? "정상" : "삭제"}</Text>
    </Flex>
  );
};

export default React.memo(PartnerListItem);
