// src/components/molecules/listitem/ReservationListItem.tsx
import React from "react";
import Flex from "../../atoms/Layouts/Flex";
import Text from "../../atoms/Text/Text";
import { Link } from "react-router-dom";

type Props = {
  reservation: any;
};

const ReservationListItem = ({ reservation }: Props) => {
  return (
    <Flex height="50px">
      <Text width="5%">
        <Link to={`/adm/reservation/${reservation.id}`}>{reservation.id}</Link>
      </Text>
      <Text width="15%">
        <Link to={`/adm/reservation/${reservation.id}`}>
          {reservation.reservationNum}
        </Link>
      </Text>
      {/* <Text width="10%">{reservation.createTime.substr(0, 9)}</Text> */}
      <Text width="10%">
        {reservation.paidAt.replace("T", " ").split(".")[0]}
      </Text>
      <Text width="5%">{reservation.isCancel ? "취소" : "결제"}</Text>
      <Text width="10%">{reservation.reservationDate}</Text>
      <Flex direction="column" gap="10px" width="15%">
        <Text>{reservation.memberNickName}</Text>
        <Text color="grey">{reservation.phoneNumber}</Text>
      </Flex>
      <Text width="20%">{reservation.productTitle}</Text>
      <Text width="10%">
        {typeof reservation.amount === "number"
          ? reservation.amount.toLocaleString()
          : reservation.amount}
      </Text>
    </Flex>
  );
};

export default ReservationListItem;

// src/components/molecules/list/ReservationListItem.svelte
<script lang="ts">
  import LinkedText from "../../atoms/links/LinkedText.svelte";
  import Text from "../../atoms/texts/Text.svelte";
  import ListItemLayout from "../../layouts/ListItemLayout.svelte";
  import type { ReservationItem } from "../../utils/Types";
  import TwoValueText from "./TwoValueText.svelte";

  export let item: any;
</script>

<ListItemLayout>
  <button
    class="txt"
    on:click={() => {
      alert(JSON.stringify(item, null, 2));
    }}
  >
    {item.reservationNum}
  </button>
  <Text width="12%">
    {item.createTime.substr(0, 9)}
  </Text>
  <Text width="12%">
    {item.isCancel ? "취소" : "결제"}
  </Text>
  <Text width="12%">
    {item.reservationDate}
  </Text>
  <TwoValueText
    width="12%"
    val1={item.memberNickName}
    val2={item.phoneNumber}
  />
  <Text width="28%">
    {item.productTitle}
  </Text>
  <Text width="12%">
    {item.amount}
  </Text>
</ListItemLayout>

<style>
  .txt {
    width: 12%;
    font-size: 16px;
    text-align: center;
  }
</style>
