// src/components/molecules/listitem/SectionListItem.tsx
import React from "react";
import Flex from "../../atoms/Layouts/Flex";
import Text from "../../atoms/Text/Text";
import { Link } from "react-router-dom";

type Props = {
  section: any;
};

const SectionListItem = ({ section }: Props) => {
  return (
    <Flex height="50px">
      <Text width="15%">
        <Link to={`/adm/section/${section.id}`}>{section.id}</Link>
      </Text>
      <Flex width="40%" direction="column" gap="0px">
        <Link to={`/adm/section/${section.id}`}>
          <Text>{section.title}</Text>
        </Link>
      </Flex>
      <Text width="15%">{section.priority}</Text>
      <Text width="15%">{section.productCnt}</Text>
      <Text width="15%">{section.useYn ? "T" : "F"}</Text>
    </Flex>
  );
};

export default SectionListItem;

// src/components/molecules/list/SectionListItem.svelte
<script lang="ts">
	import LinkedText from "../../atoms/links/LinkedText.svelte";
	import Text from "../../atoms/texts/Text.svelte";
	import ListItemLayout from "../../layouts/ListItemLayout.svelte";

	interface SectionItem {
		id: number;
		title: string;
		priority: number;
		productCnt: number;
		useYn: boolean;
	}

	export let item: SectionItem = {
		id: 0,
		title: "제목",
		priority: 0,
		productCnt: 0,
		useYn: true,
	};
</script>

<ListItemLayout>
	<Text width="20%">{item.id.toLocaleString()}</Text>
	<LinkedText to="/section/{item.id}" width="25%">{item.title}</LinkedText>
	<Text width="20%">{item.priority.toLocaleString()}</Text>
	<Text width="20%">{item.productCnt.toLocaleString()}</Text>
	<Text width="15%">{item.useYn ? "사용 중" : "사용 안함"}</Text>
</ListItemLayout>
