// src/components/organisms/list/MemberList.tsx
import React, { useCallback, useState } from "react";
import useSWR from "swr";
import Search from "../common/Search";
import ListWrapper from "../../atoms/Layouts/ListWrapper";
import Panel from "../../atoms/Layouts/Panel";
import ListHead from "../../molecules/listitem/ListHead";
import Spinner from "../../atoms/Spinner/Spinner";
import PageChanger from "../../molecules/list/PageChanger";
import Flex from "../../atoms/Layouts/Flex";
import MemberApi from "../../../libs/apis/MemberApi";
import Button from "../../atoms/Button/Button";
import { Link } from "react-router-dom";
import MemberListItem from "../../molecules/listitem/MemberListItem";

const MemberList = () => {
  const [maxPage, setMaxPage] = useState(10);
  const [searchOption, setSearchOption] = useState<any>({
    pageNum: 1,
    pageSize: 10,
  });
  const fetcher = async () => {
    const res = await MemberApi.getMemberList(searchOption);
    if (res.status === 200) {
      console.log(res.data);
      setMaxPage(res.data.totalPages);
    }
    return res;
  };
  const { data, isLoading, isValidating } = useSWR(
    ["getMemberList", searchOption],
    fetcher
  );

  const changeSort = (e: string) => {
    let temp = { ...searchOption };
    temp["pageNum"] = 1;
    if (e === "ID") {
      if (temp["sortType"] === "new") {
        temp["sortDirection"] =
          temp["sortDirection"] === "desc" ? "asc" : "desc";
      } else {
        temp["sortType"] = "new";
        temp["sortDirection"] = "desc";
      }
    } else if (e === "구매") {
      if (temp["sortType"] === "buyCnt") {
        temp["sortDirection"] =
          temp["sortDirection"] === "desc" ? "asc" : "desc";
      } else {
        temp["sortType"] = "buyCnt";
        temp["sortDirection"] = "desc";
      }
    } else if (e === "후기") {
      if (temp["sortType"] === "review") {
        temp["sortDirection"] =
          temp["sortDirection"] === "desc" ? "asc" : "desc";
      } else {
        temp["sortType"] = "review";
        temp["sortDirection"] = "desc";
      }
    } else if (e === "구매금액") {
      if (temp["sortType"] === "paid") {
        temp["sortDirection"] =
          temp["sortDirection"] === "desc" ? "asc" : "desc";
      } else {
        temp["sortType"] = "paid";
        temp["sortDirection"] = "desc";
      }
    }
    setSearchOption(temp);
  };

  const search = useCallback((tgt: string, query: string) => {
    let temp: any = {
      pageNum: 1,
      pageSize: 10,
    };
    if (query !== "") {
      if (tgt === "이메일") temp["email"] = query;
      else if (tgt === "닉네임") temp["nickname"] = query;
      else if (tgt === "전화번호") temp["cellphone"] = query;
      else if (tgt === "지역") temp["location"] = query;
      else if (tgt === "등급") {
        if (query === "VIP" || query === "vip") temp["grade"] = 1;
        else if (query.includes("절친")) temp["grade"] = 2;
        else if (query.includes("친구")) temp["grade"] = 3;
      }
    }
    setSearchOption(temp);
  }, []);

  return (
    <ListWrapper>
      <Flex align="space-between">
        <Search
          target={["이메일", "닉네임", "전화번호", "지역", "등급"]}
          submit={search}
        />
        <Button color="black" width="70px" onClick={() => {}}>
          <Link to="/adm/member/add">등록</Link>
        </Button>
      </Flex>
      <Panel>
        <ListHead
          titles={[
            "ID",
            "닉네임(이메일)",
            "등급",
            "연락처",
            "후기",
            "구매",
            "구매금액",
            "상태",
            "최종 접속",
          ]}
          sizes={[
            "10%",
            "20%",
            "10%",
            "10%",
            "10%",
            "10%",
            "10%",
            "10%",
            "10%",
          ]}
          clickable={[
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
          ]}
          changeSort={changeSort}
        />
        {(isLoading || isValidating) && <Spinner height="550px" />}
        {/* {isLoading === false &&
          data.status === 200 &&
          data.data.content.map((item: any) => {
            return (
              <MemberListItem key={`member_${item.id}`} member={item} />
            );
          })} */}
      </Panel>

      <PageChanger
        pageNum={searchOption["pageNum"]}
        maxPage={maxPage}
        setPageNum={(page: number) => {
          setSearchOption({ ...searchOption, pageNum: page });
        }}
      />
    </ListWrapper>
  );
};

export default MemberList;

// src/components/organisms/member/MemberList.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { push } from "svelte-spa-router";
	import GreyBackgroundButton from "../../atoms/buttons/GreyBackgroundButton.svelte";
	import SpaceBetween from "../../atoms/layouts/SpaceBetween.svelte";
	import GreyText from "../../atoms/texts/GreyText.svelte";
	import ListItemLayout from "../../layouts/ListItemLayout.svelte";
	import ListLayout from "../../layouts/ListLayout.svelte";
	import SearchLayout from "../../layouts/SearchLayout.svelte";
	import MemberListItem from "../../molecules/list/MemberListItem.svelte";
	import PageSelector from "../../molecules/list/PageSelector.svelte";
	import TwoValueGreyText from "../../molecules/list/TwoValueGreyText.svelte";
	import Loading from "../../molecules/loading/Loading.svelte";
	import Search from "../../molecules/search/Search.svelte";
	import Select from "../../molecules/search/Select.svelte";
	import TransparentSelect from "../../molecules/search/TransparentSelect.svelte";
	import APIs from "../../utils/APIs";
	import type { SelectType } from "../../utils/Types";

	let searchStandards: SelectType[] = [
		{ id: 1, name: "아이디", value: 1 },
		{ id: 2, name: "닉네임", value: 2 },
		{ id: 3, name: "연락처", value: 3 },
		{ id: 4, name: "지역", value: 4 },
	];
	let sortStandards: SelectType[] = [
		{ id: 1, name: "가입일순", value: "new" },
		{ id: 2, name: "후기순", value: "review" },
		{ id: 3, name: "구매수순", value: "buyCnt" },
		{ id: 4, name: "구매금액순", value: "paid" },
	];
	let sortOrder: SelectType[] = [
		{ id: 1, name: "내림차순", value: "desc" },
		{ id: 2, name: "오름차순", value: "asc" },
	];
	let sortGrade: SelectType[] = [
		{ id: 1, name: "등급 전체", value: -1 },
		{ id: 2, name: "VIP", value: 1 },
		{ id: 3, name: "반차 절친", value: 2 },
		{ id: 4, name: "반차 친구", value: 3 },
	];
	let searchQuery: string = "";
	let selectedSearchStandard: SelectType = searchStandards[0];
	let selectedStandard: SelectType = sortStandards[0];
	let selectedOrder: SelectType = sortOrder[0];
	let selectedGrade: SelectType = sortGrade[0];

	let curPage: number = 1;
	let maxPage: number = 20;
	let rangeMin: number = 1;

	let list = [];
	let loading = true;

	onMount(() => {
		getMembers(1);
	});

	const getMembers = (page: number) => {
		loading = true;

		let option = { pageSize: 10 };
		option["pageNum"] = page;
		if (searchQuery !== "") {
			if (selectedSearchStandard.value === 1) {
				option["email"] = searchQuery;
			} else if (selectedSearchStandard.value === 2) {
				option["nickname"] = searchQuery;
			} else if (selectedSearchStandard.value === 3) {
				option["cellphone"] = searchQuery;
			} else if (selectedSearchStandard.value === 4) {
				option["locaion"] = searchQuery;
			}
		}
		option["sortType"] = selectedStandard.value;
		option["sortDirection"] = selectedOrder.value;
		if (selectedGrade.value !== -1) {
			option["grade"] = selectedGrade.value;
		}

		APIs.getMember(option).then((res) => {
			if (res.status === 200) {
				console.log(res.data.content);
				list = res.data.content;
				maxPage = res.data.totalPages;
				loading = false;
			} else {
				alert("불러오기 에러!");
			}
		});
		curPage = page;
	};

	let addMember = () => {
		push("/member/new");
	};

	const search = () => {
		getMembers(1);
		curPage = 1;
		rangeMin = 1;
	};
</script>

<SearchLayout>
	<SpaceBetween gap="20px" alignItems="end">
		<Select
			lists={searchStandards}
			bind:selected={selectedSearchStandard}
			borderRadius={true}
		/>
		<Search onEnter={search} bind:value={searchQuery} />
		<TransparentSelect lists={sortStandards} bind:selected={selectedStandard} />
		<TransparentSelect lists={sortOrder} bind:selected={selectedOrder} />
		<TransparentSelect lists={sortGrade} bind:selected={selectedGrade} />
	</SpaceBetween>
	<GreyBackgroundButton
		onClick={addMember}
		width="100px"
		height="30px"
		fontSize="16px">+ 회원 추가</GreyBackgroundButton
	>
</SearchLayout>

<ListLayout>
	<ListItemLayout head={true}>
		<GreyText width="10%">회원번호</GreyText>
		<TwoValueGreyText width="20%" val1="이메일" val2="닉네임" />
		<GreyText width="8%">등급</GreyText>
		<GreyText width="10%">연락처</GreyText>
		<GreyText width="10%">후기</GreyText>
		<GreyText width="10%">구매</GreyText>
		<GreyText width="10%">구매금액</GreyText>
		<GreyText width="8%">상태</GreyText>
		<TwoValueGreyText width="14%" val1="최종접속일" val2="가입일" />
	</ListItemLayout>
	{#if loading}
		<Loading />
	{:else}
		{#each list as item}
			<MemberListItem {item} />
		{/each}
	{/if}
</ListLayout>

<PageSelector bind:curPage {maxPage} bind:rangeMin onClick={getMembers} />
